language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r karaoke-webservice *
  - mkdir -p deploy
  - mv karaoke-webservice.zip deploy/karaoke-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: karaoke-webservice-deploy #S3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: wlehwjdgh/karaoke-webservice #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: karaoke-webservice-deploy # S3 버킷
    key: karaoke-webservice.zip # S3 버킷에 저장된 karaoke-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: karaoke-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: karaoke-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: wlehwjdgh/karaoke-webservice
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - wlehwjdgh4@naver.com