spring:
  profiles:
    active: local # 기본 환경 선택
  #  active: set1 # 기본 환경 선택
  #jpa:
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
server:
  port: 1234
spring:
  profiles: local
  datasource:
  #  data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true# 운영 환경

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082